Repository appwex/facebook-clone, pull requests merged in 2022-12, with the labels that each got.

#12 Add Story Component
  package.json
  pages/home/Homepage.js
  pages/home/Homepage.module.scss
  pages/home/index.js
  pages/index.js
  pages/stories/Stories.module.scss
  pages/stories/exampleComponent.js
  pages/stories/index.js
  src/components/examplecomponent/ExampleComponent.js
  src/components/examplecomponent/ExampleComponent.module.scss
  src/components/examplecomponent/index.js
  src/components/stories/Stories.js
  src/components/stories/Stories.module.scss
  src/components/stories/index.js
  yarn.lock
Labels: ready for review

#23 Add Story Component Usage
  Docs/Story_Component_Use_Case.md
Labels: documentation

#25 Configure Path
  jsconfig.json
  pages/stories/exampleComponent.js
Labels: enhancement

#26 Add Icon Button
  next.config.js
  package.json
  pages/stories/iconButton.js
  pages/stories/index.js
  src/assets/addIcon.svg
  src/assets/arrow-down.svg
  src/assets/arrow-right.svg
  src/assets/callIcon.svg
  src/assets/forwardIcon.svg
  src/assets/friendIcon.svg
  src/assets/gamingIcon.svg
  src/assets/homeIcon.svg
  src/assets/marketPlaceIcon.svg
  src/assets/menuIcon.svg
  src/assets/messengerIcon.svg
  src/assets/notificationIcon.svg
  src/assets/optionIcon.svg
  src/assets/searchIcon.svg
  src/assets/watchIcon.svg
  src/components/iconbutton/IconButton.js
  src/components/iconbutton/IconButton.module.scss
  src/components/iconbutton/index.js
  styles/colors.scss
  styles/common.scss
  yarn.lock
Labels: ready for review

#27 Add Button Component
  pages/stories/button.js
  pages/stories/index.js
  src/components/button/Button.js
  src/components/button/Button.module.scss
  src/components/button/index.js
  src/components/examplecomponent/ExampleComponent.js
  src/components/examplecomponent/ExampleComponent.module.scss
  src/components/examplecomponent/index.js
  styles/colors.scss
Labels: ready for review

#28 Add Tab link Component
  pages/stories/button.js
  pages/stories/exampleComponent.js
  pages/stories/index.js
  pages/stories/tablink.js
  src/assets/friendIcon.svg
  src/assets/homeIcon.svg
  src/assets/marketPlaceIcon.svg
  src/assets/plus.svg
  src/assets/watchIcon.svg
  src/components/button/Button.js
  src/components/button/Button.module.scss
  src/components/tablink/Tablink.js
  src/components/tablink/Tablink.module.scss
  src/components/tablink/index.js
  styles/colors.scss
Labels: ready for review

#29 Add Search bar Component
  pages/stories/index.js
  pages/stories/searchbar.js
  src/assets/search-icon.svg
  src/components/button/Button.js
  src/components/button/Button.module.scss
  src/components/searchbar/Searchbar.js
  src/components/searchbar/Searchbar.module.scss
  src/components/searchbar/index.js
  styles/colors.scss
  styles/common.scss
Labels: ready for review

#30 Add Menu Items Component
  pages/stories/button.js
  pages/stories/iconButton.js
  pages/stories/index.js
  pages/stories/menuItems.js
  pages/stories/searchbar.js
  pages/stories/tablink.js
  src/assets/adsManagementIcon.svg
  src/assets/announcementIcon.svg
  src/assets/bloodIcon.svg
  src/assets/buisinessManagerIcon.svg
  src/assets/climateScienceCentIcon.svg
  src/assets/covid19InformIcon.svg
  src/assets/crisisResponseIcon.svg
  src/assets/digitalCollectiblesIcon.svg
  src/assets/emotionalHealthIcon.svg
  src/assets/eventsIcon.svg
  src/assets/favouritesIcon.svg
  src/assets/friendsIcon2.svg
  src/assets/fundRaisersIcon.svg
  src/assets/gamingIcon2.svg
  src/assets/groupsIcon.svg
  src/assets/liveVideosIcon.svg
  src/assets/marketPlaceIcon2.svg
  src/assets/memoriesIcon.svg
  src/assets/messengerIcon2.svg
  src/assets/messengerKidsIcon.svg
  src/assets/mostRecentIcon.svg
  src/assets/orders&PaymentsIcon.svg
  src/assets/pagesIcon.svg
  src/assets/playGamesIcon.svg
  src/assets/recentAdActivityIcon.svg
  src/assets/reelsIcon.svg
  src/assets/savedIcon.svg
  src/assets/watchIcon2.svg
  src/components/button/Button.js
  src/components/button/Button.module.scss
  src/components/iconbutton/IconButton.js
  src/components/iconbutton/IconButton.module.scss
  src/components/menuitems/MenuItems.js
  src/components/menuitems/MenuItems.module.scss
  src/components/menuitems/index.js
  src/components/searchbar/Searchbar.js
  src/components/searchbar/Searchbar.module.scss
  src/components/tablink/Tablink.js
  src/components/tablink/Tablink.module.scss
  styles/colors.scss
Labels: ready for review

#31 Add Avatar Button
  next.config.js
  pages/stories/avatarButton.js
  pages/stories/index.js
  pages/stories/menuItems.js
  src/assets/img/profile.jpg
  src/assets/svg/addIcon.svg
  src/assets/svg/adsManagementIcon.svg
  src/assets/svg/announcementIcon.svg
  src/assets/svg/arrow-down.svg
  src/assets/svg/arrow-right.svg
  src/assets/svg/bloodIcon.svg
  src/assets/svg/buisinessManagerIcon.svg
  src/assets/svg/callIcon.svg
  src/assets/svg/climateScienceCentIcon.svg
  src/assets/svg/covid19InformIcon.svg
  src/assets/svg/crisisResponseIcon.svg
  src/assets/svg/digitalCollectiblesIcon.svg
  src/assets/svg/emotionalHealthIcon.svg
  src/assets/svg/eventsIcon.svg
  src/assets/svg/favouritesIcon.svg
  src/assets/svg/forwardIcon.svg
  src/assets/svg/friendIcon.svg
  src/assets/svg/friendsIcon2.svg
  src/assets/svg/fundRaisersIcon.svg
  src/assets/svg/gamingIcon.svg
  src/assets/svg/gamingIcon2.svg
  src/assets/svg/groupsIcon.svg
  src/assets/svg/homeIcon.svg
  src/assets/svg/liveVideosIcon.svg
  src/assets/svg/marketPlaceIcon.svg
  src/assets/svg/marketPlaceIcon2.svg
  src/assets/svg/memoriesIcon.svg
  src/assets/svg/menuIcon.svg
  src/assets/svg/messengerIcon.svg
  src/assets/svg/messengerIcon2.svg
  src/assets/svg/messengerKidsIcon.svg
  src/assets/svg/mostRecentIcon.svg
  src/assets/svg/notificationIcon.svg
  src/assets/svg/optionIcon.svg
  src/assets/svg/orders&PaymentsIcon.svg
  src/assets/svg/pagesIcon.svg
  src/assets/svg/playGamesIcon.svg
  src/assets/svg/recentAdActivityIcon.svg
  src/assets/svg/reelsIcon.svg
  src/assets/svg/savedIcon.svg
  src/assets/svg/searchIcon.svg
  src/assets/svg/watchIcon.svg
  src/assets/svg/watchIcon2.svg
  src/components/avatarButton/AvatarButton.js
  src/components/avatarButton/AvatarButton.module.scss
  src/components/avatarButton/index.js
Labels: ready for review

#32 Add Add-Post Manager
  pages/stories/Stories.module.scss
  pages/stories/addPostManager.js
  pages/stories/iconButton.js
  pages/stories/index.js
  pages/stories/menuItems.js
  pages/stories/searchbar.js
  pages/stories/tablink.js
  src/assets/svg/feelingActivityIcon.svg
  src/assets/svg/gridViewIcon.svg
  src/assets/svg/lifeEvent.svg
  src/assets/svg/listViewIcon.svg
  src/assets/svg/liveVideoIcon.svg
  src/assets/svg/photoVideoIcon.svg
  src/assets/svg/plus.svg
  src/assets/svg/search-icon.svg
  src/assets/svg/tagPeopleIcon.svg
  src/components/addPostManager/AddPostManager.js
  src/components/addPostManager/AddPostManager.module.scss
  src/components/addPostManager/index.js
  src/components/avatarButton/AvatarButton.js
  src/components/avatarButton/AvatarButton.module.scss
  src/components/button/Button.module.scss
  src/components/iconbutton/IconButton.js
  src/components/iconbutton/IconButton.module.scss
  src/components/menuitems/MenuItems.js
  src/components/menuitems/MenuItems.module.scss
  src/components/searchbar/Searchbar.js
  src/components/searchbar/Searchbar.module.scss
  src/components/tablink/Tablink.js
  src/components/tablink/Tablink.module.scss
  styles/colors.scss
  styles/common.scss
Labels: ready for review

#33 Add Post-Settings Menu
  pages/stories/Stories.module.scss
  pages/stories/index.js
  pages/stories/menuItems.js
  pages/stories/postSettingsMenu.js
  src/assets/svg/addIcon.svg
  src/assets/svg/filterIcon.svg
  src/assets/svg/postManageIcon.svg
  src/assets/svg/searchIcon.svg
  src/components/addPostManager/AddPostManager.module.scss
  src/components/button/Button.module.scss
  src/components/iconbutton/IconButton.module.scss
  src/components/postSettingsMenu/PostSetMenu.js
  src/components/postSettingsMenu/PostSetMenu.module.scss
  src/components/postSettingsMenu/index.js
  src/components/tablink/Tablink.module.scss
  styles/common.scss
Labels: ready for review

#35 Added Post Box
  pages/stories/Stories.module.scss
  pages/stories/index.js
  pages/stories/menuItems.js
  pages/stories/postBox.js
  pages/stories/searchbar.js
  src/assets/svg/commentIcon.svg
  src/assets/svg/crossIcon.svg
  src/assets/svg/facebookLikeIcon.svg
  src/assets/svg/facebookLoveIcon.svg
  src/assets/svg/gridViewIcon.svg
  src/assets/svg/likeIcon.svg
  src/assets/svg/listViewIcon.svg
  src/assets/svg/moreIcon.svg
  src/assets/svg/publicIcon.svg
  src/assets/svg/shareIcon.svg
  src/components/addPostManager/AddPostManager.module.scss
  src/components/avatarButton/AvatarButton.js
  src/components/avatarButton/AvatarButton.module.scss
  src/components/iconbutton/IconButton.module.scss
  src/components/postBox/PostBox.js
  src/components/postBox/PostBox.module.scss
  src/components/postBox/index.js
  src/components/postSettingsMenu/PostSetMenu.module.scss
  src/components/tablink/Tablink.module.scss
  styles/colors.scss
  styles/common.scss
Labels: ready for review

#37 Add Create Room Component
  pages/stories/button.js
  pages/stories/createRoom.js
  pages/stories/index.js
  pages/stories/menuItems.js
  pages/stories/postBox.js
  src/assets/plus.svg
  src/assets/search-icon.svg
  src/assets/svg/addIcon.svg
  src/assets/svg/createRoomIcon.svg
  src/assets/svg/listViewIcon.svg
  src/assets/svg/nextArrowIcon.svg
  src/assets/svg/prevArrowIcon.svg
  src/assets/svg/searchIcon.svg
  src/components/avatarButton/AvatarButton.js
  src/components/button/Button.js
  src/components/createRoom/CreateRoom.js
  src/components/createRoom/CreateRoom.module.scss
  src/components/createRoom/index.js
  src/components/iconbutton/IconButton.js
  src/components/postBox/PostBox.js
  src/components/postBox/PostBox.module.scss
  src/components/postSettingsMenu/PostSetMenu.module.scss
  src/components/searchbar/Searchbar.js
  src/components/tablink/Tablink.js
  styles/colors.scss
  styles/common.scss
Labels: ready for review

#40 Add Drop Down
  pages/stories/Stories.module.scss
  pages/stories/addPostManager.js
  pages/stories/avatarButton.js
  pages/stories/createRoom.js
  pages/stories/dropdown.js
  pages/stories/iconButton.js
  pages/stories/index.js
  pages/stories/menuItems.js
  pages/stories/postBox.js
  pages/stories/postSettingsMenu.js
  pages/stories/searchbar.js
  pages/stories/tablink.js
  src/assets/svg/hookIcon.svg
  src/components/DropDown/Dropdown.js
  src/components/DropDown/Dropdown.module.scss
  src/components/DropDown/index.js
  src/components/addPostManager/AddPostManager.js
  src/components/avatarButton/AvatarButton.js
  src/components/button/Button.js
  src/components/createRoom/CreateRoom.js
  src/components/iconbutton/IconButton.js
  src/components/menuitems/MenuItems.js
  src/components/postBox/PostBox.js
  src/components/searchbar/Searchbar.js
  src/components/tablink/Tablink.js
  src/lib/hook/index.js
  src/lib/hook/useClickOutside.js
  styles/colors.scss
  styles/common.scss
Labels: ready for review
